### ISSUE TITLE
calamares_repo.db failed to downloaderror: failed retrieving file 'calamares_repo.db' from gitlab.com : The requested URL returned error: 404

### ISSUE THREAD

**Issue by plus9a** [arch-linux-calamares-installer/alci_repo#1]
community is up to date multilib
 multilib is up to date calamares_repo
calamares_repo.db failed to downloaderror: failed retrieving file 'calamares_repo.db' from gitlab.com : The requested URL returned error: 404
error: failed to synchronize all databases (failed to retrieve some files)
==> ERROR: Failed to install packages to new root

https://gitlab.com/kazi-sifat-plus9a/calamares_repo
https://github.com/kazi-sifat-plus9a/calamares_repo

I dont know why it didn't worked ,
I am very fastrated about it.
I seen 1 hour your https://youtu.be/pT8XFGBuROs
This video and wasted 3 days . I don't want to lose 😭
There is now way i did something wrong on pacman.conf and i also removed
 sudo rm -r work

**Comment by arcolinuxz** [comment]
Use github.com and not gitlab.com

Wait a day before trying again

**Comment by plus9a** [comment]
Thanks for your replay +video + community .. it was a noob problem i didn't changed .db inside x86_64
